name: Podman quadlet info

on:
  push:
    paths:
      - ".github/workflows/podman_quadlet_info.yml"
      - ".github/workflows/reusable-module-test.yml"
      - "ci/*.yml"
      - "ci/run_containers_tests.sh"
      - "ci/playbooks/containers/podman_quadlet_info.yml"
      - "plugins/modules/podman_quadlet_info.py"
      - "plugins/module_utils/podman/quadlet.py"
      - "tests/integration/targets/podman_quadlet_info/**"
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/podman_quadlet_info.yml"
      - ".github/workflows/reusable-module-test.yml"
      - "ci/*.yml"
      - "ci/run_containers_tests.sh"
      - "ci/playbooks/containers/podman_quadlet_info.yml"
      - "plugins/modules/podman_quadlet_info.py"
      - "plugins/module_utils/podman/quadlet.py"
      - "tests/integration/targets/podman_quadlet_info/**"
  schedule:
    - cron: 5 0 * * * # Run daily at 0:05 UTC

jobs:
  test_podman_quadlet_info:
    uses: ./.github/workflows/reusable-module-test.yml
    with:
      module_name: "podman_quadlet_info"
      display_name: "Podman quadlet info"
